queue_rules:
  - name: default
    queue_branch_prefix: "ZZZPFX-"
    merge_conditions: []

pull_request_rules:
  - name: auto queue
    conditions:
      - base=main
      - label=queueme
    actions:
      queue:
        name: default
